# DS Lab Activity 1.3. Numpy Superfast Tutorial

In this tutorial we go through the basic capabilities of numpy. 

**Learning Outcomes**

1.	gain familiarity with important basic operations in numpy
2.	ability to conduct a simple matrices and arrays operations in numpy

Numpy is all about dealing with arrays efficiently. It allows us to manipulate big arrays in a fast and convenient way. We do not use built in python lists because they are slow for large arrays. Remember they allow for different types to coexist in a list. We pay less efficiency as a price for this built in flexibility. Numpy condenses all the capabilities of usual numerical packages or software such as MATLAB or R (if you are familiar with these). For more details see [official numpy quick start](https://numpy.org/doc/stable/user/quickstart.html).


First we always need to import the library that we want to use, in our case the library is numpy and for abbreviation we called it np. 

In [1]:
%matplotlib inline
from IPython.display import display, HTML
display(HTML('<style>.container {width: 85% !important}</style>'))

In [2]:
import numpy as np

Each time we want to invoke a function from numpy we do something like np.fun() where fun() is the name of the function that we want to call. For example, numpy has a function called arange() that is similar to the usual python range() function but produces iterable list in an efficient way.

In [3]:
a = np.arange(2,10)
print(a)

[2 3 4 5 6 7 8 9]


In [4]:
a = np.arange(4,10)  # multiply all by 10
print(a*10)

[40 50 60 70 80 90]


In [5]:
ap = np.arange(5)**2  # raise all to the power of 10
print(ap)

[ 0  1  4  9 16]


To obtain the sum we can do the following

In [6]:
ap.sum()

30

## We can now slice

In [7]:
print(a)
print(a[:-3])
print(a[:3])

[4 5 6 7 8 9]
[4 5 6]
[4 5 6]


In [8]:
print(a[:-1]) # print all except the last element

[4 5 6 7 8]


In [9]:
print(a[:-2]) # print all except the last 2 elements

[4 5 6 7]


Although the following is not generally advisable in data science or machine learning, we can go through the elements of an array one by one. It is better and more Pythonic to manipulate the array as is without treating each element separately. This is called vectorisation and constitutes an important aspect of machine learning algorithms

In [10]:
for row in a:
    print(row)

4
5
6
7
8
9


## We can deal with multi-dimensional arrays

The following generates numbers 0<=x<1

In [11]:
rg = np.random.default_rng(1)     # for random number generation
a = rg.random((3,4))
print(a)

a = rg.random((3,4))
print(a)

[[0.51182162 0.9504637  0.14415961 0.94864945]
 [0.31183145 0.42332645 0.82770259 0.40919914]
 [0.54959369 0.02755911 0.75351311 0.53814331]]
[[0.32973172 0.7884287  0.30319483 0.45349789]
 [0.1340417  0.40311299 0.20345524 0.26231334]
 [0.75036467 0.28040876 0.48519097 0.9807372 ]]


we can generate numbers 0<x<10 by multiplying by 10

In [12]:
# run this multiple times each time you will get a different set of numbers (different array) which is what we want
a = rg.random((2,3))*10
print(a)

[[9.61657194 7.24789941 5.41226856]
 [2.76891204 1.60652009 9.69925413]]


## Random Integers
if we want integer we can floor

In [13]:
a = np.floor(rg.random((2,3))*10).astype(int)
print(a)

[[5 1 6]
 [7 6 9]]


Be mindful as the order makes a big difference, for example the following will always get us an array of 0s

In [14]:
a = np.floor(rg.random((2,3)))*10
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


We can call functions such as sort, sqrt and exp on the entire array efficiently

In [15]:
a = np.floor(rg.random((2,3))*10)
print(a)
print(np.sort(a))

[[5. 2. 8.]
 [5. 5. 7.]]
[[2. 5. 8.]
 [5. 5. 7.]]


In [16]:
print(np.exp(a))
print(np.sqrt(a))

[[ 148.4131591     7.3890561  2980.95798704]
 [ 148.4131591   148.4131591  1096.63315843]]
[[2.23606798 1.41421356 2.82842712]
 [2.23606798 2.23606798 2.64575131]]


The above however, is not the standard way of generating random integer. numpy provides a function that is dedicated for this task, let us see how.

In [17]:
rng = np.random.default_rng()
rng.integers(3, size=(2,10))

array([[1, 1, 1, 1, 2, 0, 2, 2, 2, 2],
       [0, 0, 2, 2, 2, 0, 0, 0, 0, 0]], dtype=int64)

## Generating an array of 1s or 0s

In [18]:
a = np.ones(6)
print(a)


[1. 1. 1. 1. 1. 1.]


In [19]:
b = np.ones((2,6))
print(b)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


Note that once we moved to multi-dimension we need to provide the space as a tuple (2,6) inside the parenthesis of the ones()

If we want to generate 1s as integers then we can either convert or set the type during the initialisation.

In [20]:
a = np.ones(6).astype(int)
print(a)
type(a)

[1 1 1 1 1 1]


numpy.ndarray

In [21]:
a = np.ones(6, dtype=np.uint32)
print(a)
type(a)

[1 1 1 1 1 1]


numpy.ndarray

## Arrays Shape

Be mindful to the shape that you are dealing with as often this is the single most common obstacle in any numpy implementation

In [22]:
a = np.ones(6)
print(a)
print(a.shape)

# same as above
a = np.ones((6,))
print(a)
print(a.shape)


[1. 1. 1. 1. 1. 1.]
(6,)
[1. 1. 1. 1. 1. 1.]
(6,)


so the above is an array of one dimension (it is neither a column nor a row)
If we want a column you should do something like the following

In [23]:
a = np.ones((6,1))   # column
print(a)

a = np.ones((1,6))   # row
print(a)


[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
[[1. 1. 1. 1. 1. 1.]]


Same as for the 0s we can produce as many as we want from them

In [24]:
a = np.zeros(6)
print(a)

[0. 0. 0. 0. 0. 0.]


The following generates an error, make sure to remember this as it will come handy when you forget about the extra parenthesis needed for the shape (6,2)

In [25]:
# a = np.zeros(6,2)

## We can transpose an array to flip its shape

In [26]:
a = np.floor(rg.random((2,3))*10)
print(a)
print(a.T)   # array transpose

[[1. 8. 6.]
 [7. 1. 8.]]
[[1. 7.]
 [8. 1.]
 [6. 8.]]


In [27]:
a = np.floor(rg.random((4,1))*10)
print(a)
print(a.T)   # array transpose

[[1.]
 [0.]
 [8.]
 [8.]]
[[1. 0. 8. 8.]]


Be mindful as this applies only to matrices, when we deal with a arrays the transpose does not work as expected.

In [28]:
a = np.floor(rg.random((4,))*10)
print(a)
print(a.T) # = a

[8. 4. 2. 0.]
[8. 4. 2. 0.]


## Checking equality

Using python built-in list

In [29]:
a = [1,2,3,0]
b = [1,2,3,0]
a==b

True

In [30]:
a = [2,2,3,0]
b = [1,2,3,0]
a==b

False

In [31]:
a = [2,2,3,1]
b = [1,2,3,0]
a==b

False

Using numpy

In [32]:
a = np.array([1,2,3,0])
b = np.array([1,2,3,0])
a==b

array([ True,  True,  True,  True])

In [33]:
import numpy as np

a = np.array([1, 2, 3, 0, 5])
b = np.array([1, 2, 3, 0])

if len(a) != len(b):
    print("Arrays have different lengths and cannot be compared directly.")
else:
    result = a == b
    print(result)

Arrays have different lengths and cannot be compared directly.


In [34]:
a = np.array([1,2,3,0])
b = np.array([1,2,3,0])
(a==b).all()

True

In [35]:
a = np.array([1,2,3,0])
b = np.array([1,2,3,1])
(a==b).all()

False

## We can create an identity matrix

In [36]:
a = np.eye(6)
print(a)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


For identity matrix we have always that a.T=a

In [37]:
print(a.T)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


## We can assign multiple elements at once

In [38]:
a = np.sort(np.floor(rg.random((10,))*10))
print(a)

a[2:6] = 1000
print(a)

a[2:6] = np.ones(6-2)
print(a)

[1. 2. 2. 4. 6. 6. 7. 8. 8. 9.]
[   1.    2. 1000. 1000. 1000. 1000.    7.    8.    8.    9.]
[1. 2. 1. 1. 1. 1. 7. 8. 8. 9.]


## Function calls

In [39]:

def f(x,y):
    return x+y  
    #return x    # uncomment to try me but comment the others
    #return y    # same as above
    #return x*y  # same as above

b = np.fromfunction(f,(5,4),dtype=int)
print(b)

[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]


## Concatenate and merge arrays along any axis

In [40]:
a = np.floor(10*rg.random((2,5)))
b = np.floor(10*rg.random((2,5)))
print(a)
print(b)
d = np.c_[a,b]    # merged along the columns
print(d)


[[8. 4. 5. 0. 6.]
 [9. 8. 8. 6. 2.]]
[[7. 2. 8. 0. 8.]
 [1. 3. 3. 6. 1.]]
[[8. 4. 5. 0. 6. 7. 2. 8. 0. 8.]
 [9. 8. 8. 6. 2. 1. 3. 3. 6. 1.]]


In [41]:
print (a)
print (b)
d = np.c_[a.T,b.T].T    # merged along the rows
print(d)

[[8. 4. 5. 0. 6.]
 [9. 8. 8. 6. 2.]]
[[7. 2. 8. 0. 8.]
 [1. 3. 3. 6. 1.]]
[[8. 4. 5. 0. 6.]
 [9. 8. 8. 6. 2.]
 [7. 2. 8. 0. 8.]
 [1. 3. 3. 6. 1.]]


In [42]:
print (a)
print (b)
d = np.r_[a,b]        # merged along the rows
print(d)

[[8. 4. 5. 0. 6.]
 [9. 8. 8. 6. 2.]]
[[7. 2. 8. 0. 8.]
 [1. 3. 3. 6. 1.]]
[[8. 4. 5. 0. 6.]
 [9. 8. 8. 6. 2.]
 [7. 2. 8. 0. 8.]
 [1. 3. 3. 6. 1.]]


The above can be achieved in many ways, we show some below

In [43]:
d = np.hstack((a,b))  # merged along the columns
print(d)

[[8. 4. 5. 0. 6. 7. 2. 8. 0. 8.]
 [9. 8. 8. 6. 2. 1. 3. 3. 6. 1.]]


In [44]:
d = np.vstack((a,b))  # merged along the rows
print(d)

[[8. 4. 5. 0. 6.]
 [9. 8. 8. 6. 2.]
 [7. 2. 8. 0. 8.]
 [1. 3. 3. 6. 1.]]


In [45]:
d = np.column_stack((a,b))   # merged along the columns
print(d)

[[8. 4. 5. 0. 6. 7. 2. 8. 0. 8.]
 [9. 8. 8. 6. 2. 1. 3. 3. 6. 1.]]


In [46]:
a = np.array((1,2,3))
b = np.array((4,5,6))
d = np.column_stack((a,b))
print(a)
print(b)
print(d)


[1 2 3]
[4 5 6]
[[1 4]
 [2 5]
 [3 6]]


## Flattening an Array

In [47]:
print(d)
print(d.ravel())

[[1 4]
 [2 5]
 [3 6]]
[1 4 2 5 3 6]


## Making Copies and Pass by Reference

Numpy passed to functions and assign by object reference which means assignment can produce surprising results and you must be aware of this

In [48]:
h = d
print(h)

[[1 4]
 [2 5]
 [3 6]]


In [49]:
h[0,0] = 500
print(h) 
print(d) 
print(d is h)

[[500   4]
 [  2   5]
 [  3   6]]
[[500   4]
 [  2   5]
 [  3   6]]
True


So both h and d are **pointing to the same array in memory** if you change one you are changing the other !!!!

## Broadcasting, Matrices and Arrays Multiplication

### Multiplication

**This is an important topic that we will make use of in later units. Make sure to understand it. See official documentation of numpy [broadcasting](https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting) for more details.**

First we have to realise that array multiplication is different than matrix multiplication in numpy.
Numpy multiply element-wise when we simply use the operators * . For example:

In [50]:
a = np.array((1,2,3))
b = np.array((4,5,6))
d = a*b
print(d)
print(d.shape)

[ 4 10 18]
(3,)


Same for multi-dimensional array

In [51]:

a = np.floor(5*rg.random((2,5)))
b = np.floor(5*rg.random((2,5)))
d = a*b
print(a)
print(b)
print('x---------------------')
print(d)

[[1. 0. 1. 2. 0.]
 [3. 1. 3. 3. 2.]]
[[4. 3. 4. 1. 2.]
 [0. 4. 1. 1. 0.]]
x---------------------
[[4. 0. 4. 2. 0.]
 [0. 4. 3. 3. 0.]]


To do matrices multiplication we can do either of two things

1- call the dot function

In [52]:
#multiply and sum along the columns of a and b
print (a)
print (b)
d = a.dot(b.T)
print(d)

[[1. 0. 1. 2. 0.]
 [3. 1. 3. 3. 2.]]
[[4. 3. 4. 1. 2.]
 [0. 4. 1. 1. 0.]]
[[10.  3.]
 [34. 10.]]


In [53]:
#multiply and sum along the rows of a and b
print (a)
print (b)
d = a.T.dot(b)
print(d)
print(d.shape)

[[1. 0. 1. 2. 0.]
 [3. 1. 3. 3. 2.]]
[[4. 3. 4. 1. 2.]
 [0. 4. 1. 1. 0.]]
[[ 4. 15.  7.  4.  2.]
 [ 0.  4.  1.  1.  0.]
 [ 4. 15.  7.  4.  2.]
 [ 8. 18. 11.  5.  4.]
 [ 0.  8.  2.  2.  0.]]
(5, 5)


2 - convert the arrays into numpy matrices and then perform the multiplication operation *

In [54]:
p = np.matrix(a)
q = np.matrix(b)

Now we can do the usual matrices operations 

In [55]:
#multiply and sum along the columns of p and q
p*q.T

matrix([[10.,  3.],
        [34., 10.]])

In [56]:
#multiply and sum along the rows of p and q
p.T*q

matrix([[ 4., 15.,  7.,  4.,  2.],
        [ 0.,  4.,  1.,  1.,  0.],
        [ 4., 15.,  7.,  4.,  2.],
        [ 8., 18., 11.,  5.,  4.],
        [ 0.,  8.,  2.,  2.,  0.]])

### using @ operators
In Python > 3.5 we can use the @ operator to indicate that we want to do a matrices multiplication. 

In [57]:
a = np.floor(5*rg.random((3,2)))
b = np.floor(5*rg.random((3,3)))
d = a.T@b

print(a.T)
print(b)
print('x---------------------')
print(d)

[[1. 3. 1.]
 [3. 0. 2.]]
[[3. 2. 2.]
 [4. 3. 1.]
 [2. 1. 0.]]
x---------------------
[[17. 12.  5.]
 [13.  8.  6.]]


Note that $b = a \times a^\top$ is always a symmetric square matrix (not rectangular) even when $a$ is rectangular. It is actually the definition of matrices squaring operation! The diagonal of the resultant matrix is the sum of the squares of all element of each row. Equivalently, $c = a ^\top \times a$ is a symmetric square matrix, with a diagonal representing the sum of the squares of all element of each columns. Let us see an example.

In [58]:
a = np.array([[1, 2, 1],
              [1, 3, 1]])
b = a.T@a
print('the idm of the matrix = ', a.shape)
print(a.T)
print(a)
print('x--------------- cancles the 1st dim and we obtain 3x3 matrix')
print(b)

print()

c = a@a.T
print(a)
print(a.T)
print('x-------------- cancles the 2nd dim and we obtain 2x2 matrix')
print(c)

the idm of the matrix =  (2, 3)
[[1 1]
 [2 3]
 [1 1]]
[[1 2 1]
 [1 3 1]]
x--------------- cancles the 1st dim and we obtain 3x3 matrix
[[ 2  5  2]
 [ 5 13  5]
 [ 2  5  2]]

[[1 2 1]
 [1 3 1]]
[[1 1]
 [2 3]
 [1 1]]
x-------------- cancles the 2nd dim and we obtain 2x2 matrix
[[ 6  8]
 [ 8 11]]


### Symmetrical and positive definite matrix
If a matrix $a$ satisfies that $b=x^\top a x > 0$ for *all x $\in \cal R $* then we say that matrix $a$ is positive definite. See [here](https://en.wikipedia.org/wiki/Square_matrix#Definite_matrix) for more details.

In [64]:
dim = int(input('matrix dim = '))
# a = np.array([[3, 3, 3], [3, 2, 2], [3, 2, 1]])
a = np.eye(dim, dtype=np.uint64) # when we use I we obtain the sume of squares of x (remember y=Iy=yI)

# y = np.array([10, 20, 30]).reshape(3,1)
y = np.array([int(i) for i in input('input ' +str(dim) +' numbers y = ').split()]).reshape(dim,1)

print(y.T)
print(a)
print(y)
print('x---------------')
b = y.T@a@y
print(b)
print((y**2).sum())

matrix dim =  3
input 3 numbers y =  4 7 9


[[4 7 9]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[4]
 [7]
 [9]]
x---------------
[[146.]]
146


Note that even if we have a positive results for one, two or several examples, that does not prove that the matrix is positive definite, to arrive to such conclusion we need to prove that the results is *always* positive regardless of y.

### Broadcasting

In [ ]:
a = np.floor(5*rg.random((2,5)))
b = np.floor(5*rg.random((2,1)))

print(a)
print(b)


Let us broadcast b on a

In [ ]:
d = a*b
print(d)

i.e. broadcasting b on a takes each element of the first row of 'a' and multiply it by first row of 'b' and same for the second rows of 'a' and 'b'

note that 'a' and 'b' must agree on one axis and the second axis must have a dimension of 1 to be able to do the broadcasting, for example the following code will produce an error

In [ ]:
a = np.floor(5*rg.random((2,5)))
b = np.floor(5*rg.random((2,3)))

print(a)
print(b)

# d = a*b  # an error
# print(d)

In [ ]:
a = np.floor(5*rg.random((2,5)))
b = np.floor(5*rg.random((2,5)))

print(a)
print(b)

d = a*b  # element-wise multiplication 
print(d)

In [ ]:
a = np.floor(5*rg.random((2,5)))
b = np.floor(5*rg.random((1,5)))

print(a)
print(b)

d = a*b  # broadcasting 
print(d)